import { WorkspaceTemplate, ProjectType, WorkspaceFile } from '../types';

const README_CONTENT = `
# Your New Project Workspace

Welcome! This workspace has been generated to give your project a solid, organized foundation.

## Version Control Ready

This structure is ready for version control with Git. Two key files have been included to help you get started:

*   **\`README.md\` (This File):** This is the front door to your project. You should edit it to include a clear project description, setup instructions for collaborators, and any other essential information. A well-maintained README is crucial for project success.
*   **\`.gitignore\`:** This file is pre-configured to tell Git which files and folders to ignore (e.g., build artifacts, dependency folders, secret keys). This ensures your repository stays clean and only contains important source code and assets.

---

# Getting Started with Git

This workspace is ready for version control. Follow these steps to initialize a Git repository and start tracking your project.

## 1. Initialize a New Repository

Open a terminal in the root directory of this project and run:

\`\`\`bash
git init
\`\`\`

This will create a new \`.git\` subdirectory in your project folder, which contains all the necessary repository files.

## 2. Add and Commit Your Files

Stage all the files in your project for the first commit:

\`\`\`bash
git add .
\`\`\`

Now, commit the files to the repository's history:

\`\`\`bash
git commit -m "Initial commit: Set up project structure"
\`\`\`

## 3. Connect to a Remote Repository (e.g., GitHub)

If you have created a new repository on a platform like GitHub, you can connect your local repository to it.

First, copy the remote repository URL (you can find this on your GitHub repository page). Then, add it as a remote:

\`\`\`bash
git remote add origin YOUR_REPOSITORY_URL_HERE
\`\`\`

Verify the new remote:
\`\`\`bash
git remote -v
\`\`\`

## 4. Push Your Commits

Push your initial commit to the remote repository:

\`\`\`bash
git push -u origin master
\`\`\`
(Note: Your default branch might be \`main\` instead of \`master\`).

You're all set! Your project is now under version control.
`;

const RESEARCH_GITIGNORE_CONTENT = `
# Compiled source #
###################
*.com
*.class
*.dll
*.exe
*.o
*.so

# Packages #
############
# it's better to unpack these files and commit the raw source
# git has its own built in compression methods
*.7z
*.dmg
*.gz
*.iso
*.jar
*.rar
*.tar
*.zip

# Logs and databases #
######################
*.log
*.sql
*.sqlite

# OS generated files #
######################
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Temporary files from Word, Excel, PowerPoint #
###############################################
~$*.docx
~$*.xlsx
~$*.pptx
`;

const GAME_GITIGNORE_CONTENT = `
# Builds
/Build/
/build/

# Temporary files
/Temp/
/temp/
/Obj/
/obj/

# User-specific files
/Library/
/library/
*.sln.DotSettings.user
*.suo
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Autogenerated project files
/Assets/AssetStoreTools*
/Assets/Plugins/Editor/JetBrains*
ExportedObj/
.vs/
*.csproj
*.unityproj
*.sln
`;

const CUSTOM_GITIGNORE_CONTENT = `
# Dependencies
/node_modules
/.pnp
.pnp.js

# Production
/build
/dist
.next/

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Other
.env
.env.local
.env.development.local
.env.test.local
.env.production.local
`;


export const RESEARCH_TEMPLATE: WorkspaceTemplate = {
  title: 'Academic Research Project',
  description: 'A structured workspace for academic research, ensuring all components from project management to dissemination are organized and accessible.',
  structure: [
    {
      type: 'folder',
      name: '01_Project_Management',
      description: 'Core planning and administrative documents.',
      children: [
        { type: 'file', name: 'Project_Proposal.docx', description: 'The main proposal document outlining the research.' },
        { type: 'file', name: 'Project_Plan.mpp', description: 'Timeline, milestones, and resource allocation.' },
        { type: 'file', name: 'Budget.xlsx', description: 'Financial planning and tracking.' },
        { type: 'file', name: 'Meeting_Notes.md', description: 'Minutes and action items from team meetings.' },
        {
          type: 'folder',
          name: 'Task_Management',
          description: 'Kanban-style task tracking for project sprints.',
          children: [
             {
              type: 'folder',
              name: 'Backlog',
              description: 'All pending tasks and ideas.',
              children: [],
            },
            {
              type: 'folder',
              name: 'InProgress',
              description: 'Tasks currently being worked on.',
              children: [],
            },
            {
              type: 'folder',
              name: 'Completed',
              description: 'Finished tasks.',
              children: [],
            },
            { type: 'file', name: 'Sprint_Plan.md', description: 'Goals and tasks for the current sprint.' },
            { type: 'file', name: 'Task_Board.csv', description: 'A simple CSV-based task board for tracking.' },
          ]
        }
      ],
    },
    {
      type: 'folder',
      name: '02_Ethics_And_Governance',
      description: 'Documents related to ethical review and compliance.',
      children: [
        { type: 'file', name: 'Ethics_Application.pdf', description: 'Submission to the Institutional Review Board (IRB).' },
        { type: 'file', name: 'Consent_Forms.docx', description: 'Templates for participant consent.' },
        { type: 'file', name: 'Participant_Information_Sheet.pdf', description: 'Information provided to participants.' },
      ],
    },
    {
      type: 'folder',
      name: '03_Literature',
      description: 'Collection of existing research and resources.',
      children: [
        { type: 'file', name: 'Literature_Review_Matrix.xlsx', description: 'Spreadsheet to track and synthesize papers.' },
        { type: 'file', name: 'Bibliography.bib', description: 'Reference manager file (e.g., for Zotero, Mendeley).' },
        { type: 'folder', name: 'Papers', description: 'Storage for downloaded articles and PDFs.', children: [
            { type: 'file', name: 'Author2023_Key_Paper.pdf', description: 'An important reference paper.' }
        ] },
      ],
    },
    {
      type: 'folder',
      name: '04_Methods_And_Experiment',
      description: 'Protocols, designs, and materials for the study.',
      children: [
        { type: 'file', name: 'Research_Protocol.docx', description: 'Step-by-step experimental procedure.' },
        { type: 'file', name: 'Survey_Instruments.pdf', description: 'Questionnaires or surveys used in the study.' },
        { type: 'folder', name: 'Stimuli', description: 'Experimental materials presented to participants.', children: [
             { type: 'file', name: 'image_stimulus_01.png', description: 'Example stimulus material.' }
        ] },
      ],
    },
    {
      type: 'folder',
      name: '05_Data',
      description: 'Raw and processed data, and analysis scripts.',
      children: [
        { type: 'folder', name: 'Raw_Data', description: 'Original, untouched data collected from the study.', children: [
            { type: 'file', name: 'participant_01_data.csv', description: 'Untouched data from a participant.' }
        ] },
        { type: 'folder', name: 'Processed_Data', description: 'Cleaned, transformed, and prepared data for analysis.', children: [
             { type: 'file', name: 'cleaned_data.csv', description: 'Data after cleaning and preparation.' }
        ] },
        { type: 'folder', name: 'Analysis_Scripts', description: 'Code used for data analysis and generating results.', children: [
             { type: 'file', name: 'data_analysis.R', description: 'R script for statistical analysis.' },
             { type: 'file', name: 'visualizations.py', description: 'Python script for generating plots.' }
        ] },
      ],
    },
    {
      type: 'folder',
      name: '06_Dissemination',
      description: 'Outputs for sharing research findings.',
      children: [
        { type: 'folder', name: 'Manuscript', description: 'Drafts and final version of the research paper.', children: [
            { type: 'file', name: 'Draft_v1.docx', description: 'First draft of the research paper.' },
            { type: 'file', name: 'Figures_and_Tables.pptx', description: 'Editable figures and tables.' }
        ] },
        { type: 'folder', name: 'Presentations', description: 'Slideshows for conferences and talks.', children: [
            { type: 'file', name: 'Conference_Presentation.pptx', description: 'Slides for a conference talk.' }
        ] },
        { type: 'file', name: 'Poster.ai', description: 'Poster for a symposium (Adobe Illustrator file).' }
      ],
    },
    { type: 'file', name: 'README.md', description: 'Overview of the project workspace, goals, and key contacts.', content: README_CONTENT },
    { type: 'file', name: '.gitignore', description: 'Specifies intentionally untracked files to ignore.', content: RESEARCH_GITIGNORE_CONTENT }
  ],
  keyPoints: [
    { title: 'Abstract', description: 'A concise summary of the entire project.' },
    { title: 'Introduction', description: 'Introduces the problem, provides context, and presents the research question.' },
    { title: 'Literature Review', description: 'Summarizes and evaluates existing knowledge on the topic, identifying gaps.' },
    { title: 'Methodology', description: 'Details the methods, tools, and procedures used for data collection and analysis.' },
    { title: 'Results', description: 'Presents the findings clearly, often with tables and graphs.' },
    { title: 'Discussion', description: 'Interprets the results, connects them to existing literature, and discusses their significance.' },
    { title: 'Conclusion', description: 'Summarizes key findings, their impact, and suggests directions for future research.' },
    { title: 'References', description: 'Lists all sources cited in the paper.' },
  ]
};

export const GAME_TEMPLATE: WorkspaceTemplate = {
  title: 'Game Development Project',
  description: 'An organized workspace for game development, separating assets, scripts, and logic for efficient collaboration and scalability.',
  structure: [
    {
      type: 'folder',
      name: 'Project',
      description: 'Root folder containing all project-related files.',
      children: [
        { type: 'folder', name: 'Assets', description: 'All game assets.', children: [
            { type: 'folder', name: 'Models', description: '3D models for characters, environments, and props (.fbx, .obj).', children: [
                { type: 'file', name: 'Player.fbx', description: '3D model for the player.' },
            ] },
            { type: 'folder', name: 'Textures', description: 'Image files used for materials and surfaces (.png, .tga).', children: [
                { type: 'file', name: 'Player_Diffuse.png', description: 'Color texture for the player.' },
            ] },
            { type: 'folder', name: 'Audio', description: 'Sound effects and music files (.wav, .mp3).', children: [
                { type: 'file', name: 'Jump.wav', description: 'Sound effect for jumping.' }
            ] },
        ] },
        { type: 'folder', name: 'Scripts', description: 'All game logic and code.', children: [
            { type: 'folder', name: 'Client', description: "Code that runs on the player's machine (e.g., input, UI).", children: [
                { type: 'file', name: 'PlayerController.cs', description: 'Handles player input and movement.' },
                { type: 'file', name: 'UIManager.cs', description: 'Manages UI state and events.' },
            ] },
            { type: 'folder', name: 'Server', description: 'Code that runs on the server (e.g., game logic, state management).', children: [
                { type: 'file', name: 'GameManager.cs', description: 'Controls the main game loop and state.' },
                { type: 'file', name: 'NPC_AI_Controller.cs', description: 'Handles enemy AI behavior.' },
            ] },
            { type: 'folder', name: 'Shared', description: 'Code accessible by both client and server (e.g., data structures).', children: [
                { type: 'file', name: 'Constants.cs', description: 'Global constants and configurations.' },
                { type: 'file', name: 'NetworkEvents.cs', description: 'Definitions for client-server communication.' }
            ] },
        ] },
        { type: 'folder', name: 'ThirdParty', description: 'External libraries and plugins.', children: [
            { type: 'folder', name: 'SomeAnalyticsSDK', description: 'Example folder for an external SDK or library.', children: [] }
        ]},
        { type: 'folder', name: 'Builds', description: 'Compiled versions of the game.', children: [
            { type: 'folder', name: 'Windows', description: 'Build for Windows platform.', children: [] },
            { type: 'folder', name: 'Mac', description: 'Build for macOS platform.', children: [] },
            { type: 'folder', name: 'Linux', description: 'Build for Linux platform.', children: [] }
        ] },
        { type: 'folder', name: 'Documentation', description: 'Design documents and project documentation.', children: [
            { type: 'file', name: 'GameDesignDocument.md', description: 'The GDD for the project.' },
            { type: 'file', name: 'ArtStyleGuide.pdf', description: 'Guidelines for visual assets.' },
        ] },
      ],
    },
     { type: 'file', name: 'README.md', description: 'Overview of the project, setup instructions, and team roles.', content: README_CONTENT },
     { type: 'file', name: '.gitignore', description: 'Specifies intentionally untracked files to ignore.', content: GAME_GITIGNORE_CONTENT }
  ],
  keyPoints: [
    { title: 'Use Folders for Grouping', description: 'Group related assets logically (e.g., players, enemies, levels) to keep the project clean.' },
    { title: 'Separate Client vs. Server Logic', description: 'Keep scripts that run on the user\'s machine (Client) separate from those on the server to ensure security and clarity.' },
    { title: 'Consistent Naming Conventions', description: 'Use a consistent naming scheme (e.g., PascalCase for files, prefixing for assets like "T_Player_Diffuse") to make assets easy to find.' },
    { title: 'Isolate Third-Party Code', description: 'Keep any code or plugins from external sources in a dedicated folder to simplify updates and prevent conflicts.' },
    { title: 'Centralize Reusable Modules', description: 'Store modules, libraries, or manager classes that are used globally in a shared or centralized location for easy access.' },
    { title: 'Manage Shared and Server-Only Assets', description: 'Use platform-specific features (like Roblox\'s ReplicatedStorage vs. ServerStorage) to control asset accessibility.' },
  ],
};

export const CUSTOM_TEMPLATE: WorkspaceTemplate = {
  title: 'Custom Project',
  description: 'A blank slate for your custom project. Add, remove, and rename folders and files to fit your needs perfectly.',
  structure: [
    {
      type: 'folder',
      name: 'src',
      description: 'Source code for the project.',
      children: [],
    },
    {
      type: 'folder',
      name: 'docs',
      description: 'Documentation files.',
      children: [],
    },
    { type: 'file', name: 'README.md', description: 'Project overview and setup instructions.', content: README_CONTENT },
    { type: 'file', name: '.gitignore', description: 'Specifies intentionally untracked files to ignore.', content: CUSTOM_GITIGNORE_CONTENT }
  ],
  keyPoints: [
    { title: 'Fully Customizable', description: 'Rename, add, or remove any folder or file to match your project\'s requirements.' },
    { title: 'Start Clean', description: 'Begin with a minimal structure and build it out as your project grows.' },
    { title: 'Universal Starting Point', description: 'A generic structure suitable for any type of project, from web apps to personal utilities.' },
  ]
};


export const WORKSPACE_TEMPLATES: Record<ProjectType, WorkspaceTemplate> = {
  [ProjectType.Research]: RESEARCH_TEMPLATE,
  [ProjectType.Game]: GAME_TEMPLATE,
  [ProjectType.Custom]: CUSTOM_TEMPLATE,
};
